
server:
  port: 9090

spring:
  application:
    name: Api-Bicicletas
  datasource:
    url: jdbc:h2:~/bicicletas
    username: admin 
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
 